### ISSUE TITLE
Не работает /fspcars

### ISSUE THREAD

**Issue by Dogstazzzy** [romanespit/Fire-Department-Helper#6]
Репорт о баге
1. Ваша версия скрипта (/fd → версия в названии окна): 1.2.4
2. Описание проблемы (подробно): После обновления игрового мода 22.11.2024г в /lmenu для руководства добавился новый пункт, и из-за этого сломалась команда /fspcars. Нужно поменять номер строчки в айди диалога. Функция спавна была 3 строчкой, стала 4.
3. Как воспроизвести проблему (пошагово): Не требуется. Решение описано выше.
4. Скриншоты/видеозапись: Не требуется.

**Comment by romanespit** [comment]
Спасибо за репорт.
Исправлено в [1.2.5](https://github.com/romanespit/Fire-Department-Helper/releases/tag/1.2.5)
